name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
