name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: tranto/FlickrImageViewer
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
